config/routes.rb
Rails.application.routes.draw do
  delete '/projects/:id', to: 'projects#delete', as: 'delete_project'
  resources :users, only: [:show]
  resources :types, only: [:show] do
    resources :projects, only: [:show]
  end
  resources :parts, only: [:show]
  resources :projects, except: [:delete]
  
  get '/', to: 'projects#index', as: "home"
  get '/signin', to: 'sessions#new', as: 'signin'
  post '/signin', to: 'sessions#create'
  post '/login', to: 'sessions#login', as: 'login'
  delete '/logout', to: 'sessions#logout', as: 'logout'
  get '/signup', to: 'users#new', as: 'signup'
  post '/signup', to: 'users#create', as: 'new_user'
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/project/:id/parts/quantities/new', to: 'parts#quantities', as: 'quantity' 
  patch '/project/:id/parts/quantities/edit', to: 'parts#quantity_update', as: 'quantity_update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/part.rb
class Part < ApplicationRecord
  has_many :project_parts
  has_many :projects, through: :project_parts
  accepts_nested_attributes_for :project_parts, allow_destroy: true
  validates :name, presence: true
  
  def get_quantity(project)
    ProjectPart.find_by()
  end


end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_parts
  has_many :parts, through: :project_parts
  belongs_to :user
  belongs_to :type

  has_many_attached :images
  
  accepts_nested_attributes_for :parts, allow_destroy: true

  validates :name, presence: true
  validates :brief_description, presence: true
  validates(:brief_description, { :length => { :in => 6..255 } })
  validates :images, attached: true
  validates :images, limit: {min: 1, max: 10, message: "- Attach 1- 10 photos"}
  scope :public_projects, -> {where("public = true")}
end

app/models/project_part.rb
class ProjectPart < ApplicationRecord
  belongs_to :part
  belongs_to :project
  #accepts_nested_attributes_for :part
  def self.set_quantity(project, part, quantity)
    ProjectPart.where(project_id: @project.id, part_id: part.id).first.quantity
  end

end

app/models/type.rb
class Type < ApplicationRecord
  has_many :projects
  scope :type, ->(type) {where("name = ?", type)}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :projects
  has_secure_password
  validates :email, uniqueness: true
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :email, presence: true
  validates(:password, { :length => { :in => 6..20 } })
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  SIGN_IN_ERROR ="You need to be logged in to view this page"

end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :require_login

  def show
    @part = Part.find_by(id: params[:id])
  end

  def quantities
    @project = Project.find_by(id: params[:id])
    @quantities = []
  end

  def quantity_update
    @project = Project.find_by(id: params[:id])
    part_params.each_key do |key|
      project_part = @project.project_parts.find_by(part_id: key)
      project_part.quantity = part_params[key][:quantity]
      project_part.save
    end
    redirect_to project_path(@project)
  end
  
  private
  def require_login
    redirect_to signin_path unless session.include? :user_id
  end

  def part_params
    params.require(:part).permit!
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_login
  skip_before_action :require_login, only: [:index]
  before_action :get_project, only: [:show, :delete, :update, :edit]

  def new
    @project = Project.new
    @parts = Part.all
    render 'new'
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = session[:user_id]
    @project.save
    @project.part_ids += existing_parts
    if @project.save
      @project.images.purge
      @project.images.attach(project_params[:images])
      if @project.parts.any?
        redirect_to quantity_path(@project) and return
      end
      redirect_to project_path(@project)
    else
      @parts = Part.all
      render :new
    end
  end

  def index
    if params[:search]
      @projects = Project.where(["public = ? and name = ?", "true", "#{params[:search]}"] )
    else
      @projects = Project.public_projects
    end
  end

  def show
  
  end

  def delete
    if @project.user == helpers.current_user
      @project.destroy
      redirect_to user_path(@project.user)
    else
      flash[:warning] = "Unable to delete a different user's project!"
      redirect_to project_path(@project)
    end
  end

  def edit
    @parts = Part.where.not(id: @project.part_ids)
  end

  def update
    @project.update(project_params)
    @project.part_ids += existing_parts
    if @project.save
      if !project_params[:images].nil?
        @project.images.purge
        @project.images.attach(project_params[:images])
      end
      if @project.parts.any?
        redirect_to quantity_path and return
        render 'parts/new'
      end
      redirect_to project_path(@project)
    else
      render :new
    end
  end

  private
  
  def require_login
    flash[:notice] = SIGN_IN_ERROR
    redirect_to signin_path unless session.include? :user_id
  end

  def get_project
    @project = Project.find_by(id: params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :brief_description, :main_description, :public, :type_id, :user_id, images: [], parts_attributes: [:id, :name, :description, :link, :created_at, :updated_at, :_destroy])
  end

  def part_params
    params.require(:project).permit(parts_attributes: [:name, project_part: [:quantity]])
  end

  def existing_parts
    params.require(:project).permit(parts: [])[:parts]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    if auth
      user = User.find_or_create_by(uid: auth['uid']) do |u|
        u.name = auth['info']['name']
        u.email = auth['info']['email']
        u.password = SecureRandom.hex(4)
      end
      session[:user_id] = user.id
      redirect_to user_path(user)
    end  
  end

  def login
    user = User.find_by(name: user_params[:name])
    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:notice] = "Incorrect Login Credentials"
      redirect_to '/signin'
    end
  end

  def logout
    session.delete :user_id
    redirect_to home_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :require_login


  def show
    if Type.find_by(name: params[:id].titleize) == nil
      @projects = Project.where(type_id: params[:id])
    else
      type = Type.find_by(name: params[:id].titleize)
      @projects = Project.where(type_id: type.id)
    end
  end

  private

  def require_login
    flash[:notice] = SIGN_IN_ERROR
    redirect_to signin_path unless session.include? :user_id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(id: params[:id])
    @projects = Project.where(user: @user)
  end

  def new
    @user = User.new
    render 'new'
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in?
    session.include? :user_id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end
end

app/helpers/parts_helper.rb
module PartsHelper
  def quantity_field(part)
    project_part = @project.project_parts.find_by(part_id: part.id)
    project_part.quantity
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def format_time(date)
    date.strftime("%m/%d/%y %H:%M")
  end

  def quantity(part)
    ProjectPart.where(project_id: @project.id, part_id: part.id).first.quantity
  end

end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light nav">
  <a class="navbar-brand" href="/">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/projects/new">Create new project <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Browse by Type
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% Type.all.each do |type| %>
            <%= link_to type.name, type_path(type.name.downcase), class: "dropdown-item" %>
          <%end%>
        </div>
    </ul>
      <div class="nav-item">
        <% if logged_in? %>
          <%= link_to "#{current_user.name.titleize}", user_path(current_user), class: "nav-link", id: "nav_color" %>
        <% else %>
          <a class="nav-link" href="/signup">Sign up</a>
        <% end %>
      </div>
      <div class="nav-item">
        <% if logged_in? %>
          <%= link_to "Logout", logout_path, method: "delete", class: "nav-link", id: "nav_color" %>
        <% else %>
          <a class="nav-link" href="/signin">Sign in</a>
        <% end %>
      </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectLog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
      <%= yield %>
  </body>
</html>

app/views/parts/_form.html.erb
<div class="container">
<h4>Enter Quantities</h4>
<%= form_tag quantity_update_path(@project), method: 'patch', layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10" do %>
  <% @project.parts.each do |part| %>
    <div class="form-group">
    <%= label_tag part.name %>
    <%= number_field_tag "part[#{part.id}][quantity]", nil, placeholder: 'quantity', value: quantity_field(part)%>
    </div>
  <% end %>
  <%= submit_tag %>
  
<% end %>

</div>

app/views/parts/quantities.html.erb
<%= render 'form' %>

app/views/parts/show.html.erb
<div class="container">
  <h3><%= @part.name %></h3>
  <br>
  <p><%= @part.description %></p>
  <br>
  <%= link_to "Click her to view part webpage", @part.link unless @part.link.empty?%>


</div>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @project.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= bootstrap_form_for(@project, label_errors: true, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f|%>
  <%= f.text_field :name, control_col: "col-sm-3" %> <br>
  <%= f.form_group do %>
    <%= f.check_box :public, inline: true, layout: :default, name: "project[public]" %> 
  <% end %>
  <%= f.collection_radio_buttons :type_id, Type.all, :id, :name %>
  <%= f.text_field :brief_description %>
  <%= f.text_area :main_description %>
  <%= f.file_field :images, multiple: true, name: "project[images][]", control_col: "col-sm-4", placeholder: "Select mutliple images" %>
  <br>

  
  <%= f.collection_check_boxes :parts, @parts, :id, :name %>
  <%= f.fields_for :parts do |part| %>
    <%= render 'part_fields', :f => part %>
  <% end %>
  <%= f.label "Add a new part" %>

  <div class="links">
  <%= link_to_add_association "Add part", f, :parts%>
  </div>
  <%= f.submit %>
<% end %>

app/views/projects/_index.html.erb
<div class="card-deck">
  <div class="card-columns">
    <% @projects.each do |project| %>
      <div class="card">
        <%= image_tag(project.images[0], class: "card-img-top" ) unless project.images.empty? %>
        <div class="card-body">
          <h5 class="card-title"><%= project.name %></h5>
          <p class="card-text"> <%= project.brief_description %></p>
          <a href=<%="/types/#{project.type.name.downcase.parameterize}/projects/#{project.id}" %> class="stretched-link"></a>
        </div>
        <div class="card-footer">
          <small class="text-muted">Created by: <%= project.user.name.titleize %></small> <br>
          <small class="text-muted">On: <%= format_time(project.created_at) %></small>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_part_fields.html.erb
<div class="nested-fields">
  <div class="field">
    
    <%= f.text_field :name, inline: true%>
    <%= f.text_field :description, inline: true %>
    <%= f.text_field :link %>


    <%= link_to_remove_association "remove", f %>
  </div>

</div>

app/views/projects/edit.html.erb
<div class="container">
  <h5>Edit project</h5>
  <br>
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<br>
<div class="title">
  <h1>All Projects</h1>
</div>
<br>
<%= form_tag projects_path, method: 'get' do %>
  <%= label_tag(:search, "search") %>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("search") %>
<% end %>
<%=render 'index' %>

app/views/projects/new.html.erb
<div class="container">
  <h5>Create a new project</h5>
  <br>
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<br>



<div class="container">
  <% if flash[:warning] %>
    <div class="notice"><%= flash[:warning] %></div>
  <% end %>
  <nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><a href=<%="/types/#{@project.type.name.downcase}" %>><%= @project.type.name %></a></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @project.name %></li>
  </ol>
  </nav>
  <div class="title"><h1><%= @project.name %></h1></div>
  <br>
  <div class="brief_description"><%= @project.brief_description %></div>
  <br>
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <% @project.images.each_with_index do |image, index| %>
        <% if index == 0 %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" class="active"></li> 
        <% else %>
          <li data-target="#carouselExampleIndicators" data-slide-to="<%= index %>" ></li> 
        <% end %>
      <% end %>
    </ol>
    <div class="carousel-inner">
      <% @project.images.each_with_index do |image, index| %>
        <div class="<%=  "carousel-item #{"active" if index == 0}" %>">
          <%= image_tag(image) %>
        </div> 
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br>
  <br>
  <div class="creator">
    <h3>Created by: <%= link_to @project.user.name.titleize, user_path(@project.user) %></h3>
    <h6>Date added: <%= format_time(@project.created_at) %></h6>
    <h6><%= @project.public ? "This page is public" : "This page is private"%></h6>
  </div>

  <br>
  <br>
  <h3>Parts and Materials</h3>
    <div class="list-group">
      <% @project.parts.each do |part| %>
        <li class="list-group-item d-flex justify-content-between align-items-center"><%= link_to part.name, part_path(part) %>
          <span class="badge badge-primary badge-pill"><%= quantity(part) %></span>
        </li>
      <% end %>
    </div>
  <br>

  <h3>Description</h3>
  <p><%= @project.main_description %></p>
  <br>
  <% if @project.user == current_user %>
    <%= link_to "Edit this project", edit_project_path, class: "btn btn-primary" %>
    <%= link_to "Delete this project", delete_project_path(@project), class: "btn btn-danger", method: 'delete' %>
  <% end %>
</div> 

app/views/types/show.html.erb
<br>
<div class="title">
  <h1><%= @projects.first.type.name unless @projects.empty? %></h1>
</div>
<br>
<%= render 'projects/index' %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= bootstrap_form_for(@user, url: new_user_path, label_errors: true, layout: :horizontal, label_col: "col-sm-2", control_col: "col-sm-10") do |f| %>
  <%= f.text_field :name, control_col: "col-sm-4" %>
  <%= f.text_field :email, control_col: "col-sm-4" %>
  <%= f.password_field :password, control_col: "col-sm-4" %>
  <%= f.submit %>  Or  <%= link_to('Log in with Google!', '/auth/google_oauth2') %> 

<% end %>

app/views/users/new.html.erb
<div class="container">
  <h5>Create a new user</h5>
  <%= render 'form' %>

</div>

app/views/users/show.html.erb
<br>
<div class="title">
  <h3>Projects by <%= @user.name.titleize %></h3>
</div>  
<br>

<div class="card-deck">
  <div class="card-columns">
    <% @projects.each do |project| %>
      <div class="card">
        <%= image_tag(project.images[0], class: "card-img-top" ) unless project.images.empty? %>
        <div class="card-body">
          <h5 class="card-title"><%= project.name %></h5>
          <p class="card-text"> <%= project.brief_description %></p>
          <a href=<%="/projects/#{project.id}" %> class="stretched-link"></a>
        </div>
        <div class="card-footer">
          <small class="text-muted">Created: <%= format_time(project.created_at) %></small>
        </div>
      </div>
    <% end %>
  </div>
</div>